import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { Activity, ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, BookOpen, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, Clock3, Cpu, Gauge, Inbox, LayoutDashboard, Leaf, Menu, Package, Pause, Play, Radio, RefreshCw, Route, ShieldCheck, Sprout, Sun, Tractor, TriangleAlert, Users, Warehouse, X } from 'lucide-react';
import Village from './Village';
import { getSnapshot, getIncidents } from './data';
import type { Scenario, WindowMinutes } from './data';

type Detail = { type: 'partner' | 'service' | 'queue' | 'dlq' | 'capacity' | 'help' | 'incident'; name?: string } | null;
const number = (n: number) => n.toLocaleString('en-US');
const routeNames = ['BCA', 'Mandiri', 'BNI', 'AstraPay'];
const scenarioNames = { outage: 'Partner outage', healthy: 'A healthy village', surge: 'Traffic surge' };

function Status({ type = 'healthy', children }: { type?: string; children: ReactNode }) {
  return <span className={`status ${type}`}><span className="status-dot" />{children}</span>;
}
function Sparkline({ variant = 'green', high = false }: { variant?: string; high?: boolean }) {
  const points = high ? '0,37 12,32 24,35 36,27 48,30 60,20 72,23 84,13 96,15 108,5 120,8' : '0,35 10,32 20,34 30,22 40,26 50,18 60,25 70,13 80,18 90,10 100,15 110,8 120,11';
  return <svg className={`sparkline ${variant}`} viewBox="0 0 124 48" aria-hidden="true"><path d={`M${points.replaceAll(' ', ' L')} L120,48 L0,48Z`} className="spark-fill"/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2" strokeLinejoin="round"/><circle cx="120" cy={high ? '8' : '11'} r="3" fill="currentColor"/></svg>;
}
function SectionLabel({ number: n, title, children }: { number: string; title: string; children?: ReactNode }) {
  return <div className="section-label"><div><span className="section-number">{n}</span><h2>{title}</h2></div>{children}</div>;
}

export default function App() {
  const [scenario, setScenario] = useState<Scenario>('outage');
  const [windowMinutes, setWindowMinutes] = useState<WindowMinutes>(15);
  const [paused, setPaused] = useState(false);
  const [ticks, setTicks] = useState(0);
  const [detail, setDetail] = useState<Detail>(null);
  const [activeNav, setActiveNav] = useState('overview');
  const [mobileNav, setMobileNav] = useState(false);
  const [acknowledged, setAcknowledged] = useState<string[]>([]);
  const [incidentFilter, setIncidentFilter] = useState('all');
  const [selectedMessages, setSelectedMessages] = useState<string[]>([]);
  const [replayedIds, setReplayedIds] = useState<string[]>([]);
  const [replayBatches, setReplayBatches] = useState<{count:number;tick:number}[]>([]);
  const [replayConfirm, setReplayConfirm] = useState(false);
  const [notice, setNotice] = useState('');
  const [lastUpdated, setLastUpdated] = useState(new Date());
  const dialogRef = useRef<HTMLDialogElement>(null);
  const snapshot = getSnapshot(scenario, windowMinutes, ticks, replayedIds.length, replayBatches);
  const incidents = getIncidents(scenario, snapshot.dlq);
  const activeIncidents = incidents.filter(i => i.status !== 'resolved');
  const selectedPartner = snapshot.partners.find(p => p.name === detail?.name);
  const failedMessages = ['TXN-48291', 'TXN-48287', 'TXN-48265', 'TXN-48253', 'TXN-48241'].filter(id => !replayedIds.includes(id));
  const visibleIncidents = incidents.filter(i => incidentFilter === 'all' || i.status !== 'resolved');

  useEffect(() => {
    if (paused) return;
    const timer = window.setInterval(() => { setTicks(t => t + 1); setLastUpdated(new Date()); }, 5000);
    return () => window.clearInterval(timer);
  }, [paused]);
  useEffect(() => {
    if (detail) dialogRef.current?.showModal();
    else dialogRef.current?.close();
  }, [detail]);
  useEffect(() => {
    if (!notice) return;
    const timer = window.setTimeout(() => setNotice(''), 5000);
    return () => window.clearTimeout(timer);
  }, [notice]);

  function changeScenario(value: Scenario) {
    setScenario(value); setTicks(0); setAcknowledged([]); setReplayedIds([]); setReplayBatches([]); setSelectedMessages([]); setReplayConfirm(false); setLastUpdated(new Date());
    setNotice(`Demo changed to: ${scenarioNames[value]}.`);
  }
  function navigate(id: string) {
    setActiveNav(id); setMobileNav(false);
    document.getElementById(id)?.scrollIntoView({ behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' });
  }
  function closeDetail() { setDetail(null); setReplayConfirm(false); }
  function replay() {
    if (scenario === 'outage' || selectedMessages.length === 0) return;
    const available = selectedMessages.filter(id => !replayedIds.includes(id));
    setReplayedIds(ids => [...ids, ...available]); setReplayBatches(batches => [...batches, {count:available.length,tick:ticks}]); setSelectedMessages([]); setReplayConfirm(false);
    setNotice(`${available.length} demo ${available.length === 1 ? 'message' : 'messages'} moved to the retry queue. No real transactions were sent.`);
  }

  const nav = [
    { id: 'overview', label: 'Overview', icon: LayoutDashboard },
    { id: 'village', label: 'Village map', icon: Tractor },
    { id: 'routes', label: 'Trading routes', icon: Route },
    { id: 'queues', label: 'Queues & retries', icon: Inbox, count: snapshot.dlq },
    { id: 'incidents', label: 'Incident journal', icon: BookOpen, count: activeIncidents.length },
  ];
  return <div className="app-shell">
    {mobileNav && <button className="nav-scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)}/>}
    <aside className={`sidebar ${mobileNav ? 'is-open' : ''}`}>
      <a className="brand" href="#overview" onClick={e => { e.preventDefault(); navigate('overview'); }}><span className="brand-mark"><Sprout size={25}/></span><span>flowstead<span className="brand-caption">MIDDLEWARE, CULTIVATED.</span></span></a>
      <div className="workspace-card"><span className="workspace-icon"><Warehouse size={19}/></span><div><strong>My homestead</strong><small>Demo environment</small></div><span className="workspace-tag">01</span></div>
      <p className="nav-label">YOUR WORKSPACE</p>
      <nav aria-label="Main navigation">{nav.map(({ id, label, icon: Icon, count }) => <button key={id} className={`nav-item ${activeNav === id ? 'active' : ''}`} onClick={() => navigate(id)} aria-current={activeNav === id ? 'page' : undefined}><Icon size={18}/><span>{label}</span>{count !== undefined && count > 0 && <span className={`nav-count ${id === 'incidents' ? 'amber' : ''}`}>{count}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="demo-card"><div className="demo-title"><Sun size={16}/><strong>A change in the weather</strong></div><p>Explore how your village responds.</p><label className="sr-only" htmlFor="scenario">Demo scenario</label><div className="select-wrap"><select id="scenario" value={scenario} onChange={e => changeScenario(e.target.value as Scenario)}>{Object.entries(scenarioNames).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><ChevronDown size={14}/></div><span className="demo-disclaimer">SIMULATED DATA · NO LIVE CONNECTION</span></div>
      <button className="help-button" onClick={() => setDetail({ type: 'help' })}><CircleHelp size={17}/> Field guide <ArrowUpRight size={15}/></button>
      <div className="engine-status"><span className="status-dot"/><span>ACE integration server<small>Engine online</small></span><Leaf size={17}/></div></div>
    </aside>

    <div className="main-shell" id="overview">
      <header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Open navigation"><Menu size={21}/></button><span>My homestead</span><ChevronRight size={13}/><strong>Overview</strong></div><div className="topbar-right"><span className="date-display"><Sun size={16}/> Monday, 5 October</span><span className="topbar-divider"/><button className="notification-button icon-button" aria-label={`${activeIncidents.length} active incidents`} onClick={() => navigate('incidents')}><Bell size={18}/>{activeIncidents.length > 0 && <span/>}</button><div className="avatar" aria-label="Operator">OP</div></div></header>
      <main>
        <div className="page-heading"><div><div className="eyebrow"><span className="little-sprout">✦</span> A FRESH LOOK AT YOUR OPERATIONS</div><h1>Good things are flowing<span>.</span></h1><p>A living view of your middleware. Every route, every message, every little detail.</p></div><div className="heading-actions"><div className={`live-label ${paused ? 'is-paused' : ''}`}><span className="status-dot"/>{paused ? 'Demo paused' : 'Live demo'}</div><div className="time-controls"><Clock3 size={15}/><label className="sr-only" htmlFor="time-window">Metrics time window</label><select id="time-window" value={windowMinutes} onChange={e => setWindowMinutes(Number(e.target.value) as WindowMinutes)}><option value={15}>Last 15 minutes</option><option value={60}>Last hour</option></select><button className="pause-button" aria-label={paused ? 'Resume demo updates' : 'Pause demo updates'} onClick={() => setPaused(!paused)}>{paused ? <Play size={14}/> : <Pause size={14}/>}</button></div></div></div>

        <div className={`notice-banner ${scenario === 'healthy' ? 'notice-healthy' : ''}`}><span className="notice-icon">{scenario === 'healthy' ? <CheckCheck size={19}/> : <TriangleAlert size={19}/>}</span><div><strong>{scenario === 'outage' ? 'One trading route needs a little care.' : scenario === 'surge' ? 'A busy day in the village. Every worker is occupied.' : 'Clear skies across your homestead.'}</strong><span>{scenario === 'outage' ? 'BNI is unreachable. Other partners are processing normally.' : scenario === 'surge' ? 'Messages are arriving faster than the workshop can process them.' : snapshot.queue > 0 ? 'All services and partners are healthy. The backlog is clearing.' : 'All services and partners are healthy. No messages are waiting.'}</span></div><button onClick={() => setDetail(scenario === 'outage' ? { type: 'partner', name: 'BNI' } : { type: 'capacity' })}>{scenario === 'outage' ? 'Inspect route' : 'View capacity'}<ArrowRight size={15}/></button></div>

        <section className="pulse-section" aria-label="Pulse check"><SectionLabel number="01" title="The pulse check"><span className="section-meta">A little peace of mind, at a glance</span></SectionLabel>
          <div className="pulse-grid"><div className="metric-card services-card"><div className="card-label"><span>Service health</span><ShieldCheck size={17}/></div><div className="health-title"><strong>{scenario === 'healthy' ? 'All is well' : 'Needs attention'}</strong><Status type={scenario === 'healthy' ? 'healthy' : 'warning'}>{scenario === 'healthy' ? '3 / 3 healthy' : scenario === 'outage' ? '2 / 3 healthy' : '1 / 3 healthy'}</Status></div><div className="service-list">{['Payment Gateway', 'Customer Sync', 'Order Processor'].map((name, i) => { const degraded = scenario === 'outage' && i === 0 || scenario === 'surge' && i !== 1; return <button key={name} onClick={() => setDetail({ type: 'service', name })}><span className={`service-dot ${degraded ? 'warning' : ''}`}/><span>{name}</span><small>{degraded ? 'Degraded' : 'Healthy'}</small><ChevronRight size={12}/></button>; })}</div></div>
          <div className="metric-card"><div className="card-label"><span>Incoming messages</span><Activity size={17}/></div><div className="metric-with-chart"><div><div className="metric-value">{snapshot.incomingRate}<span> / sec</span></div><div className="metric-hint"><span className="hint-positive"><ArrowUpRight size={13}/> {scenario === 'surge' ? 'Busy harvest' : 'Steady arrivals'}</span></div></div><Sparkline high={scenario === 'surge'}/></div><div className="metric-footer"><span><span className="small-square"/>{snapshot.completedRate} processed / sec</span><span>Rolling 60 sec</span></div></div>
          <div className="metric-card"><div className="card-label"><span>Successful deliveries</span><Package size={17}/></div><div className="metric-with-chart"><div><div className="metric-value">{snapshot.successRate.toFixed(2)}<span>%</span></div><div className="metric-hint"><span>{number(snapshot.successes)} delivered</span></div></div><div className="success-mark"><Check size={25}/></div></div><div className="metric-footer"><span className={snapshot.failures ? 'text-amber' : ''}>{snapshot.failures ? <TriangleAlert size={12}/> : <Check size={12}/>} {number(snapshot.failures)} failed · {(100-snapshot.successRate).toFixed(2)}%</span><span>of {number(snapshot.successes + snapshot.failures)} finalized</span></div></div></div>
        </section>

        <section className="traffic-section" id="village" aria-label="Traffic and speed"><SectionLabel number="02" title="Around the village"><span className="section-meta"><span className="tiny-live-dot"/> Your traffic, brought to life</span></SectionLabel><div className="village-grid"><div className="village-card"><div className="village-heading"><div><h3>The working landscape</h3><p>Every parcel has a place to go.</p></div><span className="village-weather"><Sun size={17}/> {scenario === 'surge' ? 'Harvest rush' : 'Autumn, day 5'}</span></div><div className="village-art"><Village scenario={scenario} paused={paused} onSelect={name => setDetail({ type: 'partner', name })}/></div><div className="village-legend"><span><span className="legend-square green"/>Healthy route</span><span><span className={`legend-square ${scenario === 'surge' ? 'amber' : 'red'}`}/>{scenario === 'surge' ? 'Slower responses' : 'Partner unavailable'}</span><span className="map-instruction">Select a trading post to inspect <ArrowUpRight size={12}/></span></div><div className="latency-strip"><div className="latency-title"><Gauge size={19}/><span>Delivery speed<small>Successful responses · last {windowMinutes} min</small></span></div><div><strong>{snapshot.averageLatency}<small> ms</small></strong><span>Average</span></div><div><strong>{snapshot.p95}<small> ms</small></strong><span>p95</span></div><div><strong>{snapshot.p99}<small> ms</small></strong><span>p99</span></div></div></div>
        <div className="routes-card" id="routes"><div className="panel-heading"><div><h3>Trading routes</h3><p>Your partners, at a glance.</p></div><span className="count-pill">4 partners</span></div><div className="route-table"><div className="route-table-head"><span>PARTNER</span><span>DONE / S</span><span>AVG.</span><span>SUCCESS</span></div>{snapshot.partners.map(partner => <button className={`route-row ${partner.status === 'down' ? 'route-down' : ''}`} key={partner.name} onClick={() => setDetail({ type: 'partner', name: partner.name })}><span className="partner-cell"><span className={`partner-icon ${partner.code.toLowerCase()}`}>{partner.code.slice(0,1)}</span><span><strong>{partner.name}</strong><small className={partner.status === 'down' ? 'text-red' : ''}><span className={`service-dot ${partner.status}`}/>{partner.status === 'down' ? 'Unavailable' : partner.status === 'warning' ? 'Slow' : 'Connected'}</small></span></span><span>{partner.completedRate}</span><span className={partner.status === 'down' ? 'text-red' : ''}>{partner.latency === null ? '30s timeout' : `${partner.latency} ms`}</span><span>{(partner.successes + partner.failures) > 0 ? `${(100 * partner.successes / (partner.successes + partner.failures)).toFixed(1)}%` : '—'}<ChevronRight size={13}/></span></button>)}</div><div className="route-footnote"><Radio size={13}/><span>Rates: 60s · Outcomes: {windowMinutes} min</span></div><button className="route-summary" onClick={() => setDetail({ type: 'partner', name: scenario === 'healthy' ? 'BCA' : 'BNI' })}><span className={`status-dot ${scenario === 'outage' ? 'down' : ''}`}/><span>{scenario === 'outage' ? 'BNI is offline. Your engine is healthy.' : scenario === 'surge' ? 'All routes reachable. Two partners are slow.' : 'All four trading routes are open.'}</span><ArrowRight size={15}/></button></div></div></section>

        <div className="lower-grid"><section id="queues" aria-label="Queues and reject bin"><SectionLabel number="03" title="A place for every parcel"><span className="section-meta">The shock absorber</span></SectionLabel><div className="two-card-grid"><button className="resource-card" onClick={() => setDetail({ type: 'queue' })}><div className="card-label"><span><Warehouse size={17}/> Waiting in the silo</span><ArrowUpRight size={15}/></div><div className="resource-value">{number(snapshot.queue)}<span>messages</span></div><div className="queue-meter" aria-hidden="true">{Array.from({length:24},(_,i) => <span key={i} className={i < Math.min(24, Math.ceil(snapshot.queue/90)) ? 'filled' : ''}/>)}</div><div className="resource-bottom"><span className={snapshot.queueDelta > 0 ? 'text-amber' : 'text-green'}>{snapshot.queueDelta > 0 ? <ArrowUpRight size={13}/> : <ArrowDownLeft size={13}/>} {snapshot.queueDelta > 0 ? '+' : ''}{snapshot.queueDelta} / sec</span><span>Oldest: {Math.floor(snapshot.oldestSeconds/60)}m {snapshot.oldestSeconds%60}s</span></div></button><button className="resource-card reject-card" onClick={() => setDetail({ type: 'dlq' })}><div className="card-label"><span><Inbox size={17}/> The reject bin</span><ArrowUpRight size={15}/></div><div className="resource-value">{snapshot.dlq}<span>{snapshot.dlq > 0 ? 'need a helping hand' : 'waiting for review'}</span></div><div className="reject-description">{snapshot.dlq > 0 ? 'Retries exhausted. Ready for a closer look.' : 'All reviewed. Your reject bin is clear.'}</div><div className="resource-bottom"><span className="text-amber">Inspect messages <ArrowRight size={13}/></span><span>Dead letter queue</span></div></button></div></section>
        <section id="capacity" aria-label="Engine room"><SectionLabel number="04" title="Inside the workshop"><span className="section-meta">The engine room</span></SectionLabel><div className="two-card-grid"><button className="resource-card" onClick={() => setDetail({ type: 'capacity' })}><div className="card-label"><span><Users size={17}/> Busy craftsmen</span><ArrowUpRight size={15}/></div><div className="resource-value">{snapshot.workers}<span>/ {snapshot.totalWorkers} workers</span></div><div className={`worker-icons ${snapshot.workers === 10 ? 'saturated' : ''}`} aria-label={`${snapshot.workers} of 10 workers busy`}>{Array.from({length:10},(_,i) => <Users size={18} key={i} className={i < snapshot.workers ? 'busy' : ''}/>)}</div><div className="resource-bottom"><span>{snapshot.workers * 10}% occupied</span><span>{snapshot.totalWorkers-snapshot.workers} available</span></div></button><button className="resource-card" onClick={() => setDetail({ type: 'capacity' })}><div className="card-label"><span><Cpu size={17}/> Furnace pressure</span><ArrowUpRight size={15}/></div><div className="resource-value">{snapshot.heap}<span>% heap used</span></div><div className={`meter ${snapshot.heap >= 80 ? 'warning-meter' : ''}`}><span style={{width:`${snapshot.heap}%`}}/></div><div className="resource-bottom"><span>{(snapshot.heap/100*2).toFixed(2)} / 2 GB</span><span>CPU {snapshot.cpu}%</span></div></button></div></section></div>

        <section id="incidents" className="incidents-section" aria-label="Live incident feed"><div className="journal-heading"><div className="journal-title"><BookOpen size={19}/><h2>The incident journal</h2><span className="count-pill">{activeIncidents.length} open</span></div><div className="filter-tabs" aria-label="Incident filter"><button onClick={() => setIncidentFilter('all')} aria-pressed={incidentFilter === 'all'}>All activity</button><button onClick={() => setIncidentFilter('open')} aria-pressed={incidentFilter === 'open'}>Needs attention</button></div></div><div className="incident-table-wrap"><table className="incident-table"><thead><tr><th>TIME · WIB</th><th>SERVICE / PARTNER</th><th>WHAT HAPPENED</th><th>STATUS</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{visibleIncidents.map(incident => <tr key={incident.id}><td>{incident.time}</td><td><span className={`incident-service ${incident.status}`}/>{incident.service}</td><td>{incident.message}{acknowledged.includes(incident.id) && <small className="ack-label">Acknowledged</small>}</td><td><Status type={incident.status === 'active' ? 'down' : incident.status === 'warning' ? 'warning' : 'healthy'}>{incident.status === 'active' ? 'Active' : incident.status === 'warning' ? 'Warning' : 'Resolved'}</Status></td><td><button className="icon-button" aria-label={`Inspect incident: ${incident.service}`} onClick={() => setDetail({type:'incident',name:incident.id})}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table>{visibleIncidents.length === 0 && <div className="empty-state"><CheckCheck size={24}/><strong>Nothing needs your attention.</strong><span>All incidents in this demo are resolved.</span></div>}</div><div className="journal-footer"><span><span className={`tiny-live-dot ${paused ? 'paused-dot' : ''}`}/>{paused ? 'Updates paused' : 'Listening to your village'}<span className="footer-dot">·</span>Updated {lastUpdated.toLocaleTimeString('en-GB', {timeZone:'Asia/Jakarta'})} WIB</span><span>Plain English. A clearer picture.</span></div></section>
        <footer className="page-footer"><span><Sprout size={14}/> A calmer way to keep things moving.</span><span>Flowstead <span className="footer-dot">/</span> Demo data · Asia/Jakarta</span></footer>
      </main>
    </div>

    <dialog ref={dialogRef} aria-label="Operational details" className="detail-dialog" onCancel={closeDetail} onClick={e => { if(e.target === e.currentTarget) closeDetail(); }}><div className="dialog-content"><div className="dialog-top"><span><Sprout size={18}/> FIELD NOTES</span><button className="icon-button" onClick={closeDetail} aria-label="Close details"><X size={20}/></button></div>
      {detail?.type === 'partner' && selectedPartner && <><div className={`detail-icon partner-icon ${selectedPartner.code.toLowerCase()}`}>{selectedPartner.code.slice(0,1)}</div><h2>{selectedPartner.name} trading post</h2><p className="dialog-intro">{selectedPartner.status === 'down' ? 'The partner is unreachable. The middleware engine is online, and new messages are waiting safely in the queue.' : selectedPartner.status === 'warning' ? 'The route is reachable, but successful responses are slower than normal during the traffic surge.' : 'This trading route is open and processing messages.'}</p><Status type={selectedPartner.status}>{selectedPartner.status === 'down' ? 'Partner unavailable' : selectedPartner.status === 'warning' ? 'Slow responses' : 'Connected'}</Status><div className="detail-stats"><div><span>Completed now</span><strong>{selectedPartner.completedRate} <small>msg/s</small></strong></div><div><span>{selectedPartner.latency === null ? 'Timeout threshold' : 'Average response'}</span><strong>{selectedPartner.latency === null ? '30,000' : selectedPartner.latency} <small>ms</small></strong></div><div><span>Delivered · {windowMinutes} min</span><strong>{number(selectedPartner.successes)}</strong></div><div><span>Failed · {windowMinutes} min</span><strong>{number(selectedPartner.failures)}</strong></div></div>{selectedPartner.latency === null && <div className="detail-callout"><TriangleAlert size={18}/><p>No successful latency samples are available. Repeated health probes have timed out; zero throughput alone does not determine partner health.</p></div>}<h3>Operator note</h3><p>{selectedPartner.status === 'down' ? 'Check the BNI endpoint and network path. Restore partner connectivity before replaying any failed messages. Switch the demo to “A healthy village” to explore recovery.' : 'Health probes are passing. Watch the queue trend and tail latency during higher traffic.'}</p><button className="primary-button" onClick={() => setDetail({type:'queue'})}>Inspect the waiting queue <ArrowRight size={16}/></button></>}
      {detail?.type === 'service' && <><h2>{detail.name}</h2><p className="dialog-intro">{detail.name === 'Payment Gateway' ? 'Routes payment messages to BCA, Mandiri, BNI, and AstraPay.' : detail.name === 'Customer Sync' ? 'Keeps customer records synchronized across connected systems.' : 'Validates incoming orders and passes them to downstream systems.'}</p><Status type={scenario !== 'healthy' && detail.name !== 'Customer Sync' && (scenario === 'surge' || detail.name === 'Payment Gateway') ? 'warning' : 'healthy'}>{scenario !== 'healthy' && detail.name !== 'Customer Sync' && (scenario === 'surge' || detail.name === 'Payment Gateway') ? 'Degraded' : 'Healthy'}</Status><div className="detail-callout"><ShieldCheck size={20}/><p>{scenario === 'outage' && detail.name === 'Payment Gateway' ? 'The service is running. Its degraded state comes from BNI connectivity, not an engine failure.' : scenario === 'surge' && detail.name !== 'Customer Sync' ? 'The service is running, but all shared workers are busy. New messages are accumulating in the queue.' : 'The service is online and its health checks are passing.'}</p></div><h3>Connected operations</h3>{(detail.name === 'Payment Gateway' ? routeNames : ['Shared worker pool']).map(name => <button key={name} className="detail-list-button" onClick={() => setDetail(name === 'Shared worker pool' ? {type:'capacity'} : {type:'partner',name})}>{name}<ArrowRight size={16}/></button>)}</>}
      {detail?.type === 'queue' && <><h2>The waiting silo</h2><p className="dialog-intro">Messages accepted by the middleware that have not yet reached a final outcome. Pending retries are included; dead letters are separate.</p><div className="detail-stats"><div><span>Waiting now</span><strong>{number(snapshot.queue)}</strong></div><div><span>Queue change</span><strong>{snapshot.queueDelta > 0 ? '+' : ''}{snapshot.queueDelta}<small> / sec</small></strong></div><div><span>Arrivals</span><strong>{snapshot.incomingRate}<small> / sec</small></strong></div><div><span>Processing</span><strong>{snapshot.completedRate}<small> / sec</small></strong></div></div><div className="detail-callout"><Warehouse size={20}/><p>{scenario === 'outage' ? 'BNI work is waiting for the partner to recover. At current rates, the backlog grows by 15 messages every 5 seconds.' : scenario === 'surge' ? 'All workers are busy. Current arrivals exceed processing, so the backlog is growing.' : snapshot.queue > 0 ? 'Processing capacity exceeds incoming traffic. The backlog is draining.' : 'The queue is empty. Processing now matches incoming traffic, with spare capacity available.'}</p></div><h3>Queue policy</h3><dl className="detail-definitions"><div><dt>Oldest waiting message</dt><dd>{Math.floor(snapshot.oldestSeconds/60)}m {snapshot.oldestSeconds%60}s</dd></div><div><dt>Maximum delivery attempts</dt><dd>3</dd></div><div><dt>Retry delay</dt><dd>30 seconds</dd></div><div><dt>After retry exhaustion</dt><dd>Move to reject bin</dd></div></dl><button className="primary-button" onClick={() => setDetail({type:'dlq'})}>Inspect {snapshot.dlq} dead letters <ArrowRight size={16}/></button></>}
      {detail?.type === 'dlq' && <><h2>The reject bin</h2><p className="dialog-intro">These BNI messages exhausted all 3 delivery attempts. Inspect and select messages to move them into the demo retry queue.</p>{scenario === 'outage' && <div className="detail-callout"><TriangleAlert size={18}/><p>Replay is blocked while BNI is unavailable. Choose “A healthy village” in the demo scenario control to restore connectivity.</p></div>}<div className="dead-letter-list">{failedMessages.map((id,i) => <label key={id} className="dead-letter"><input type="checkbox" checked={selectedMessages.includes(id)} onChange={e => setSelectedMessages(ids => e.target.checked ? [...ids,id] : ids.filter(v => v !== id))}/><span><strong>{id}</strong><small>BNI payment · 3 attempts · {i+2}m ago</small><span>Connection timed out after 30s</span></span><Package size={18}/></label>)}</div>{failedMessages.length === 0 ? <div className="empty-state"><CheckCheck size={28}/><strong>The reject bin is empty.</strong><span>All five demo messages were queued for retry.</span></div> : <><p className="small-detail">The overall failure count also includes terminal business rejections. It is not the same as the current dead-letter count.</p>{replayConfirm ? <div className="replay-confirm"><strong>Queue {selectedMessages.length} selected messages for replay?</strong><p>This changes the demo queue only. Each message can be replayed once.</p><div><button className="secondary-button" onClick={() => setReplayConfirm(false)}>Cancel</button><button className="primary-button" onClick={replay}>Confirm demo replay</button></div></div> : <button className="primary-button" disabled={scenario === 'outage' || selectedMessages.length === 0} onClick={() => setReplayConfirm(true)}><RefreshCw size={16}/> Replay selected ({selectedMessages.length})</button>}</>}</>}
      {detail?.type === 'capacity' && <><h2>Inside the workshop</h2><p className="dialog-intro">A shared view of worker capacity, JVM heap, and server CPU. Busy workers include threads waiting on downstream calls.</p><div className="detail-stats"><div><span>Busy workers</span><strong>{snapshot.workers} / {snapshot.totalWorkers}</strong></div><div><span>Worker saturation</span><strong>{snapshot.workers*10}%</strong></div><div><span>JVM heap used</span><strong>{snapshot.heap}%</strong></div><div><span>Server CPU</span><strong>{snapshot.cpu}%</strong></div></div><div className="detail-callout"><Cpu size={20}/><p>{scenario === 'surge' ? 'The worker pool is saturated. Queuing absorbs the burst, but sustained growth needs investigation or additional capacity.' : 'The middleware engine is online. There is spare worker capacity.'}</p></div><h3>Reading memory correctly</h3><p>Heap usage is a point-in-time measurement. A single high value does not establish a memory leak; inspect retained memory across garbage-collection cycles.</p><dl className="detail-definitions"><div><dt>Configured heap</dt><dd>2 GB</dd></div><div><dt>Used heap</dt><dd>{(snapshot.heap / 100 * 2).toFixed(2)} GB</dd></div><div><dt>Available workers</dt><dd>{10-snapshot.workers}</dd></div></dl></>}
      {detail?.type === 'incident' && (() => { const incident = incidents.find(i=>i.id===detail.name); if (!incident) return null; return <><h2>{incident.service}</h2><p className="dialog-intro">{incident.message}</p><Status type={incident.status === 'active' ? 'down' : incident.status === 'warning' ? 'warning' : 'healthy'}>{incident.status === 'active' ? 'Active' : incident.status === 'warning' ? 'Warning' : 'Resolved'}</Status><dl className="detail-definitions"><div><dt>Reported at</dt><dd>{incident.time} WIB</dd></div><div><dt>Incident reference</dt><dd>{incident.id}</dd></div><div><dt>Operator review</dt><dd>{acknowledged.includes(incident.id) ? 'Acknowledged' : 'Not yet acknowledged'}</dd></div></dl><p>Acknowledging records that you have seen this incident. Its health status changes only when the underlying issue is resolved.</p><button className="primary-button" disabled={acknowledged.includes(incident.id)} onClick={() => {setAcknowledged(ids=>[...ids,incident.id]);setNotice('Incident acknowledged. Its health status is unchanged.');}}><Check size={16}/>{acknowledged.includes(incident.id) ? 'Acknowledged' : 'Acknowledge incident'}</button></>; })()}
      {detail?.type === 'help' && <><h2>A field guide to Flowstead</h2><p className="dialog-intro">A calmer operational dashboard inspired by a working village.</p><div className="guide-list"><div><ShieldCheck/><span><strong>The pulse check</strong>Service banners tell you what needs attention. Rates use a rolling 60-second window; delivery totals use the selected time window.</span></div><div><Route/><span><strong>The trading posts</strong>Each bank has its own route. Select a stall or table row to inspect connectivity and response time.</span></div><div><Warehouse/><span><strong>The silo and reject bin</strong>The silo holds waiting work. The reject bin holds messages that exhausted their retries.</span></div><div><Users/><span><strong>The workshop</strong>Worker occupancy, memory, and CPU show how much capacity remains.</span></div></div><div className="detail-callout"><Sun size={20}/><p>This is an interactive prototype with simulated data. Scenario changes reset the demo. No monitoring backend is connected and no real transactions are replayed.</p></div></>}
    </div></dialog>
    <div className={`toast ${notice ? 'visible' : ''}`} role="status" aria-live="polite"><CheckCheck size={18}/><span>{notice}</span></div>
  </div>;
}
