import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowRight, Boxes, Check, ChevronDown, CircleHelp, Code2, Database, ExternalLink, FileJson, Grid2X2, Layers3, LoaderCircle, LockKeyhole, Radio, RefreshCw, Server, ShieldCheck, Sprout, Terminal, TriangleAlert, Wifi, WifiOff, X, Zap } from 'lucide-react';
import HeaderPulse from './components/HeaderPulse';
import ChannelMatrix from './components/ChannelMatrix';
import QueueManager from './components/QueueManager';
import EngineDiagnostics from './components/EngineDiagnostics';
import IncidentFeed from './components/IncidentFeed';
import LivingTownCanvas from './components/LivingTownCanvas';
import type { TownSelection } from './components/LivingTownCanvas';
import { useTelemetry } from './hooks/useTelemetry';
import { scenarioLabels } from '../shared/types';
import type { ActionResult, ChannelId, Incident, IncidentFilter, Scenario } from '../shared/types';
import { translateBip } from '../shared/translator';

type Selection=TownSelection | {type:'payload';id:string}|{type:'incident';incident:Incident}|{type:'confirm';id:string;action:'retry'|'discard'}|{type:'connection'}|{type:'guide'};
const format=(value:number,digits=0)=>value.toLocaleString('en-US',{maximumFractionDigits:digits});
const stamp=(value:string)=>new Date(value).toLocaleTimeString('en-GB',{timeZone:'Asia/Jakarta'});
const primaryScenarios:Scenario[]=['normal','flash_sale','bni_timeout','dlq_influx'];

export default function App(){
  const feed=useTelemetry();
  const {telemetry,diagnostics,connection,stale,pending}=feed;
  const [mode,setMode]=useState<'noc'|'town'>('noc');
  const [filter,setFilter]=useState<IncidentFilter>('ALL');
  const [query,setQuery]=useState('');
  const [selection,setSelection]=useState<Selection|null>(null);
  const [payload,setPayload]=useState<unknown>(null);
  const [payloadError,setPayloadError]=useState('');
  const [payloadLoading,setPayloadLoading]=useState(false);
  const [notification,setNotification]=useState<ActionResult|null>(null);
  const [token,setToken]=useState('');
  const [authPending,setAuthPending]=useState(false);
  const [authError,setAuthError]=useState('');
  const [now,setNow]=useState(new Date());
  const drawer=useRef<HTMLDialogElement>(null);
  const isMock=connection==='fallback'||feed.config.mode==='mock';
  const blocking=connection==='auth-required'||(connection==='unavailable'&&feed.history.length===0);
  const selectedChannel=telemetry.channels.find(channel=>channel.id===(selection&&'id' in selection?selection.id:undefined));
  const activeScenario=diagnostics?.scenario??feed.config.scenario;
  const sourceLabel=connection==='mock'?'Server simulation':connection==='fallback'?'Local fallback simulation':connection==='live'?'Live IBM telemetry':connection==='auth-required'?'Authentication required':connection==='unavailable'?'Collector unavailable':connection==='reconnecting'?'Reconnecting':'Connecting to server';
  const disabledPending=feed.canAct?pending:'disabled';

  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(selection)drawer.current?.showModal();else drawer.current?.close();},[selection]);
  useEffect(()=>{if(!notification)return;const timer=setTimeout(()=>setNotification(null),6000);return()=>clearTimeout(timer);},[notification]);
  useEffect(()=>{
    if(selection?.type!=='payload')return;
    let cancelled=false;setPayload(null);setPayloadError('');setPayloadLoading(true);
    feed.getPayload(selection.id).then(data=>{if(!cancelled)setPayload(data);}).catch(error=>{if(!cancelled)setPayloadError(error instanceof Error?error.message:'Could not read payload.');}).finally(()=>{if(!cancelled)setPayloadLoading(false);});
    return()=>{cancelled=true;};
  },[selection,feed.getPayload]);
  const close=()=>{setSelection(null);setAuthError('');setToken('');};
  function navigate(id:string){document.getElementById(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
  async function run(action:Parameters<typeof feed.execute>[0]){const result=await feed.execute(action);setNotification(result);return result;}
  async function changeScenario(scenario:Scenario){await run({type:'scenario',scenario});}
  async function confirm(){if(selection?.type!=='confirm')return;const result=await run({type:selection.action,id:selection.id});if(result.ok)close();}
  function severity(value:IncidentFilter){setFilter(value);setQuery('');navigate('incident-feed');}
  async function login(event:React.FormEvent){event.preventDefault();setAuthPending(true);setAuthError('');try{await feed.authenticate(token);setToken('');close();}catch(error){setAuthError(error instanceof Error?error.message:'Authentication failed.');}finally{setAuthPending(false);}}

  return <div className="noc-app">
    <aside className="rail"><a href="#top" className="rail-brand" aria-label="Flowstead home" onClick={event=>{event.preventDefault();navigate('top');}}><Layers3 size={24}/></a><div className="rail-divider"/><button className={mode==='noc'?'selected':''} aria-label="NOC overview" onClick={()=>{setMode('noc');navigate('top');}}><Grid2X2 size={19}/></button><button className={mode==='town'?'selected':''} aria-label="Living town simulation" onClick={()=>{setMode('town');navigate('top');}}><Sprout size={20}/></button><button aria-label="Inspect queues" onClick={()=>navigate('queue-manager')}><Boxes size={20}/></button><button aria-label="Incident feed" onClick={()=>navigate('incident-feed')}><Activity size={20}/></button><div className="rail-bottom"><button aria-label="Field guide" onClick={()=>setSelection({type:'guide'})}><CircleHelp size={20}/></button><button aria-label="Connection settings" onClick={()=>setSelection({type:'connection'})}><Server size={20}/></button><span className="operator-avatar" aria-label="Operator">OP</span></div></aside>
    <div className="workspace" id="top"><header className="app-topbar"><div className="brand-line"><strong>flowstead<span>.</span></strong><span className="topbar-slash">/</span><span className="topbar-product">Integration observatory</span><span className="environment-tag">{isMock?'SANDBOX':'LIVE CLUSTER'}</span></div><div className="topbar-status"><span className={`connection-indicator ${stale?'warning':'healthy'}`}/><span>{sourceLabel}</span><button className="icon-button" aria-label="Connection details" onClick={()=>setSelection({type:'connection'})}>{connection==='live'||connection==='mock'?<Wifi size={16}/>:<WifiOff size={16}/>}</button></div></header>
      <main className="dashboard-main"><div className="page-heading"><div><div className="eyebrow flex items-center gap-2"><span className="tiny-line"/> IBM APP CONNECT ENTERPRISE <span className="text-slate-600">/</span> IBM MQ</div><h1>Payment gateway</h1><p>Every transaction. Every partner. One shared picture.</p></div><div className="heading-meta"><span className="clock-time mono">{now.toLocaleTimeString('en-GB',{timeZone:'Asia/Jakarta'})}<small> WIB</small></span><span className="text-xs text-slate-500">{now.toLocaleDateString('en-GB',{timeZone:'Asia/Jakarta',day:'2-digit',month:'short',year:'numeric'})}</span></div></div>
      <div className="scenario-bar"><div className="scenario-label"><Zap size={15}/><span>SCENARIO LAB</span></div><div className="scenario-options">{primaryScenarios.map(scenario=><button key={scenario} onClick={()=>void changeScenario(scenario)} disabled={!isMock||!feed.canAct||pending!==null} aria-pressed={activeScenario===scenario} className={`scenario-button ${activeScenario===scenario?'active':''}`}>{scenario==='normal'?<span className="scenario-dot"/>:scenario==='flash_sale'?<Zap size={12}/>:scenario==='bni_timeout'?<Radio size={12}/>:<Boxes size={12}/>}<span>{scenarioLabels[scenario]}</span></button>)}<label className="scenario-more"><span className="sr-only">Additional simulation scenario</span><select value={activeScenario==='bca_outage'||activeScenario==='thread_starvation'?activeScenario:''} onChange={event=>{if(event.target.value)void changeScenario(event.target.value as Scenario);}} disabled={!isMock||!feed.canAct||pending!==null}><option value="">More scenarios</option><option value="bca_outage">BCA Bank Outage</option><option value="thread_starvation">Thread Starvation</option></select><ChevronDown size={12}/></label></div><span className="scenario-caption">{isMock?'No real payments':'Read-only telemetry'}</span></div>
      {(connection==='fallback'||stale||connection==='auth-required'||connection==='unavailable')&&<div className={`connection-banner ${connection==='fallback'?'fallback':'interrupted'}`} role="status"><TriangleAlert size={16}/><div><strong>{connection==='fallback'?'Local simulation fallback':connection==='auth-required'?'Operator access required':stale?'Telemetry is stale':'Collector unavailable'}</strong><span>{connection==='fallback'?'The server is unavailable. Data and actions are simulated locally; reconnecting automatically.':connection==='auth-required'?'Authenticate to receive protected telemetry.':feed.error||'The last known snapshot is retained. Manual actions are disabled until fresh telemetry arrives.'}</span></div><button onClick={()=>connection==='auth-required'?setSelection({type:'connection'}):feed.reconnect()}>{connection==='auth-required'?'Authenticate':'Reconnect'}<ArrowRight size={14}/></button></div>}
      {blocking?<section className="panel unavailable-panel"><ShieldCheck size={40}/><h2>{connection==='auth-required'?'Connect to your monitoring workspace':'No verified telemetry available'}</h2><p>{connection==='auth-required'?'Use your configured operator token to establish a secure session.':'The live collector could not provide a validated snapshot. Simulated values will not be substituted for live data.'}</p><button className="action-button" onClick={()=>setSelection({type:'connection'})}>Connection details <ArrowRight size={15}/></button></section>:<>
      <HeaderPulse telemetry={telemetry} history={feed.history} onSeverity={severity} mode={mode} onModeChange={setMode}/>
      {mode==='noc'?<ChannelMatrix telemetry={telemetry} diagnostics={diagnostics} onInspect={id=>setSelection({type:'channel',id})} onPing={async id=>{await run({type:'ping',id});}} pending={disabledPending}/>:<section className="town-view"><LivingTownCanvas telemetry={telemetry} diagnostics={diagnostics} onInspect={setSelection}/></section>}
      <div className="diagnostic-layout"><div id="queue-manager"><QueueManager telemetry={telemetry} diagnostics={diagnostics} onPayload={id=>setSelection({type:'payload',id})} onRetry={id=>setSelection({type:'confirm',id,action:'retry'})} onDiscard={id=>setSelection({type:'confirm',id,action:'discard'})} pending={disabledPending}/></div><EngineDiagnostics telemetry={telemetry} diagnostics={diagnostics} history={feed.history}/></div>
      <div id="incident-feed"><IncidentFeed incidents={telemetry.latest_incidents} filter={filter} onFilterChange={setFilter} query={query} onQueryChange={setQuery} onInspect={incident=>setSelection({type:'incident',incident})}/></div>
      </>}
      <footer className="dashboard-footer"><span><ShieldCheck size={13}/> {isMock?'SIMULATED TELEMETRY':'VERIFIED COLLECTOR SCHEMA'}<span className="footer-separator">·</span>{connection==='mock'||connection==='live'?'WebSocket · 1,000ms':sourceLabel}</span><span>{feed.lastReceived?`Last update ${stamp(telemetry.timestamp)} WIB`:'Waiting for first snapshot'}<span className="footer-separator">/</span> Flowstead v2.0</span></footer>
      </main>
    </div>

    <dialog className="inspection-drawer" ref={drawer} aria-label="Telemetry inspection" onCancel={close} onClick={event=>{if(event.target===event.currentTarget)close();}}><div className="drawer-inner"><div className="drawer-top"><span className="eyebrow"><Terminal size={14}/> TELEMETRY INSPECTOR</span><button className="icon-button" onClick={close} aria-label="Close inspector"><X size={20}/></button></div>
      {selection?.type==='channel'&&selectedChannel&&<><div className="drawer-kicker">PAYMENT CHANNEL / {selectedChannel.id}</div><h2>{selectedChannel.name}</h2><p className="drawer-intro">{selectedChannel.status==='DOWN'?'The partner endpoint is unavailable. Incoming work remains in the buffer until connectivity returns.':selectedChannel.status==='DEGRADED'?'The partner is reachable, but response latency has increased.':'The partner is reachable and accepting transactions.'}</p><span className={`status-pill ${selectedChannel.status==='UP'?'healthy':selectedChannel.status==='DOWN'?'critical':'warning'}`}><span className="status-dot"/>{selectedChannel.status}</span><div className="drawer-stats"><div><span>Throughput</span><strong>{format(selectedChannel.tps,1)}<small> TPS</small></strong></div><div><span>{selectedChannel.status==='DOWN'?'Timeout threshold':'Average response'}</span><strong>{format(selectedChannel.latency_ms)}<small> ms</small></strong></div><div><span>p95 response</span><strong>{diagnostics?.channel_p95_ms[selectedChannel.id]??'—'}<small> ms</small></strong></div><div><span>Error rate</span><strong>{format(selectedChannel.error_rate,2)}<small>%</small></strong></div></div><button className="action-button" disabled={!feed.canAct||pending!==null} onClick={()=>void run({type:'ping',id:selectedChannel.id})}><Radio size={15}/>{pending===`ping:${selectedChannel.id}`?'Checking…':isMock?'Run simulated probe':'Run health probe'}</button><h3>Recent related events</h3><div className="drawer-event-list">{telemetry.latest_incidents.filter(i=>(i.service+' '+i.raw_code).toUpperCase().includes(selectedChannel.id)).slice(0,4).map(i=><div key={i.id}><span className="mono">{stamp(i.timestamp)}</span><p>{i.plain_message}</p></div>)}{!telemetry.latest_incidents.some(i=>(i.service+' '+i.raw_code).toUpperCase().includes(selectedChannel.id))&&<p>No matching events in the recent feed.</p>}</div><h3>Raw channel telemetry</h3><pre>{JSON.stringify(selectedChannel,null,2)}</pre></>}
      {(selection?.type==='workshop'||selection?.type==='worker')&&<><div className="drawer-kicker">IBM ACE / INTEGRATION SERVER</div><h2>{selection.type==='worker'?`Worker ${selection.id??'instance'}`:'The central workshop'}</h2><p className="drawer-intro">{selection.type==='worker'?`Worker ${selection.id} is ${Number(selection.id)<=telemetry.system.active_threads?'occupied':'idle'}. Worker-level timing is not present in this telemetry contract; pool metrics are shown below.`:'Active instances include workers waiting on partner calls. Saturation above 85% warrants attention.'}</p><div className="drawer-stats"><div><span>Active / maximum</span><strong>{telemetry.system.active_threads} / {telemetry.system.max_threads}</strong></div><div><span>Heap used</span><strong>{telemetry.system.heap_memory_pct}<small>%</small></strong></div><div><span>DB active</span><strong>{telemetry.system.db_pool_active}</strong></div><div><span>DB idle</span><strong>{telemetry.system.db_pool_max-telemetry.system.db_pool_active}</strong></div></div><h3>Raw engine telemetry</h3><pre>{JSON.stringify(telemetry.system,null,2)}</pre><p className="drawer-note">Heap alone cannot diagnose a memory leak. Inspect the curve across GC cycles.</p></>}
      {selection?.type==='apps'&&<><div className="drawer-kicker">INTERNAL APPLICATIONS</div><h2>The town square</h2><p className="drawer-intro">Web and mobile applications send payment requests into the IBM MQ inbound buffer. Couriers represent message flow through the gateway.</p><div className="drawer-stats"><div><span>Ingestion</span><strong>{diagnostics?format(diagnostics.ingestion_tps,1):'—'}<small> / sec</small></strong></div><div><span>Consumption</span><strong>{diagnostics?format(diagnostics.consumption_tps,1):'—'}<small> / sec</small></strong></div></div><h3>Message path</h3><div className="message-path">Web / Mobile <ArrowRight size={14}/> IBM MQ <ArrowRight size={14}/> IBM ACE <ArrowRight size={14}/> Bank</div><p className="drawer-note">Individual customer sessions are illustrative. The telemetry contract provides aggregate traffic only.</p></>}
      {selection?.type==='queue'&&<><div className="drawer-kicker">IBM MQ / INBOUND BUFFER</div><h2>The grain silo</h2><p className="drawer-intro">Normal: 0–50 messages. Warning: 51–200. Critical: over 200. Queue pressure reflects arrivals minus consumption.</p><div className="drawer-stats"><div><span>Inbound depth</span><strong>{format(telemetry.queues.inbound_depth)}</strong></div><div><span>Dead letters</span><strong>{telemetry.queues.dlq_count}</strong></div></div><h3>Queue telemetry</h3><pre>{JSON.stringify({inbound_depth:telemetry.queues.inbound_depth,dlq_count:telemetry.queues.dlq_count,ingestion_tps:diagnostics?.ingestion_tps,consumption_tps:diagnostics?.consumption_tps},null,2)}</pre><button className="action-button" onClick={()=>{close();navigate('queue-manager');}}>Open DLQ manager <ArrowRight size={15}/></button></>}
      {selection?.type==='payload'&&<><div className="drawer-kicker">DEAD LETTER / PAYLOAD</div><h2 className="payload-title">{selection.id}</h2><p className="drawer-intro">Inspect the failed message before choosing an action. Payment idempotency keys must be preserved during retries.</p>{payloadLoading?<div className="drawer-loading"><LoaderCircle className="animate-spin" size={20}/> Loading payload…</div>:payloadError?<p className="error-message" role="alert">{payloadError}</p>:<pre>{JSON.stringify(payload,null,2)}</pre>}<div className="drawer-action-row"><button className="action-button" disabled={!feed.canAct||payloadLoading||!!payloadError||pending!==null} onClick={()=>setSelection({type:'confirm',id:selection.id,action:'retry'})}><RefreshCw size={14}/> Re-queue message</button><button className="danger-button" disabled={!feed.canAct||payloadLoading||!!payloadError||pending!==null} onClick={()=>setSelection({type:'confirm',id:selection.id,action:'discard'})}>Discard</button></div></>}
      {selection?.type==='confirm'&&<><div className="drawer-kicker">{isMock?'SIMULATION ACTION':'OPERATOR ACTION'}</div><h2>{selection.action==='retry'?'Re-queue this payment?':'Discard this message?'}</h2><p className="drawer-intro mono">{selection.id}</p><div className={`action-explanation ${selection.action==='discard'?'destructive':''}`}><TriangleAlert size={20}/><p>{selection.action==='retry'?'The message will leave the dead-letter queue and enter the inbound buffer for one retry. Its idempotency key is preserved. An unavailable partner blocks the action.':'This removes the selected message from the dead-letter queue. It will not be retried. This action cannot be undone through this dashboard.'}</p></div><p className="drawer-note">{isMock?'This is a simulation. No real payment is sent or deleted.':'This action uses your configured live action provider and affects real middleware state.'}</p><div className="drawer-action-row"><button className="subtle-button" onClick={close}>Cancel</button><button className={selection.action==='discard'?'danger-button':'action-button'} disabled={!feed.canAct||pending!==null} onClick={()=>void confirm()}>{pending?<LoaderCircle size={14} className="animate-spin"/>:null}{selection.action==='retry'?'Confirm re-queue':'Confirm discard'}</button></div></>}
      {selection?.type==='incident'&&<><div className="drawer-kicker">INCIDENT / {selection.incident.id}</div><h2>{selection.incident.service}</h2><span className={`status-pill ${selection.incident.level==='CRITICAL'||selection.incident.level==='ERROR'?'critical':selection.incident.level==='WARN'?'warning':'info'}`}><span className="status-dot"/>{selection.incident.level}</span><p className="drawer-intro mt-5">{selection.incident.plain_message}</p><h3>Original event</h3><pre>{selection.incident.raw_code}</pre><h3>BIP interpretation</h3><p className="drawer-note">{translateBip(selection.incident.raw_code).message}</p><div className="translation-disclosure"><Code2 size={15}/><span>Context-aware local rules. No AI service or external model receives event data. Verify the full exception chain before remediation.</span></div><dl className="drawer-definitions"><div><dt>Time</dt><dd>{stamp(selection.incident.timestamp)} WIB</dd></div><div><dt>Reference</dt><dd>{selection.incident.id}</dd></div></dl></>}
      {selection?.type==='connection'&&<><div className="drawer-kicker">TELEMETRY CONNECTION</div><h2>{sourceLabel}</h2><p className="drawer-intro">The same-origin WebSocket carries validated snapshots every second. Extended diagnostics are refreshed separately.</p><dl className="drawer-definitions"><div><dt>Stream</dt><dd className="mono">/ws/telemetry</dd></div><div><dt>Backend mode</dt><dd>{feed.config.mode}</dd></div><div><dt>Manual actions</dt><dd>{feed.canAct?'Enabled':'Disabled'}</dd></div><div><dt>Last received</dt><dd>{feed.lastReceived?new Date(feed.lastReceived).toLocaleTimeString('en-GB',{timeZone:'Asia/Jakarta'}):'—'} WIB</dd></div></dl>{feed.error&&<div className="error-message">{feed.error}</div>}{connection==='auth-required'||feed.config.authenticationRequired?<form onSubmit={login} className="operator-form"><label htmlFor="operator-token">Operator token</label><input id="operator-token" type="password" value={token} onChange={event=>setToken(event.target.value)} autoComplete="off" required placeholder="Enter configured operator token"/>{authError&&<p role="alert" className="error-message">{authError}</p>}<button className="action-button" disabled={authPending||!token}><LockKeyhole size={14}/>{authPending?'Authenticating…':'Establish session'}</button><p>Token is exchanged for an HttpOnly session cookie and is not stored in browser storage.</p></form>:<button className="action-button" onClick={feed.reconnect}><RefreshCw size={14}/> Reconnect stream</button>}<h3>IBM ACE & MQ integration</h3><p className="drawer-note">Configure the backend environment to use authenticated ACE administration and MQ collectors. Live mode never substitutes demo values when a collector fails. See the repository integration guide for endpoints and deployment configuration.</p></>}
      {selection?.type==='guide'&&<><div className="drawer-kicker">FLOWSTEAD / FIELD GUIDE</div><h2>One system, two perspectives.</h2><p className="drawer-intro">The NOC matrix and living town share the same validated telemetry stream. Switch views without losing the underlying state.</p><div className="guide-items"><div><Grid2X2/><span><strong>NOC operations</strong>Five payment channels, queue pressure, worker capacity, and a searchable incident feed.</span></div><div><Sprout/><span><strong>Living town</strong>Apps are a town square, ACE is a workshop, MQ is a grain silo, and banks are shipping docks. Select a building or worker to inspect its metrics.</span></div><div><ShieldCheck/><span><strong>Transparent simulation</strong>Scenario changes reset demo queues and incidents. Daily processing totals continue. A local fallback is visibly labeled if the backend disconnects.</span></div><div><Database/><span><strong>Measured diagnostics</strong>p95 excludes timeouts and is unavailable when no successful response samples exist. GC markers come from the diagnostics feed.</span></div></div><p className="drawer-note">No live IBM ACE or MQ credentials are included. Production telemetry and action providers require deployment configuration.</p></>}
      <div className="drawer-footer"><span className={`connection-indicator ${stale?'warning':'healthy'}`}/>{sourceLabel}<span className="mono">{stamp(telemetry.timestamp)} WIB</span></div>
    </div></dialog>
    {notification&&<div className={`toast ${notification.ok?'success':'failure'}`} role={notification.ok?'status':'alert'}><span>{notification.ok?<Check size={18}/>:<TriangleAlert size={18}/>}</span><p>{notification.message}</p><button onClick={()=>setNotification(null)} aria-label="Dismiss notification"><X size={15}/></button></div>}
  </div>;
}
